
import pytest
import os
import json
import hashlib
from unittest.mock import patch, MagicMock
from datetime import datetime, timezone

from retail_os.core.marketplace_adapter import MarketplaceAdapter
from retail_os.scrapers.onecheq.scraper import scrape_onecheq_product
from retail_os.core.unified_schema import normalize_onecheq_row

FIXTURE_DIR = os.path.join(os.path.dirname(__file__), "fixtures/scrapers")

def load_fixture(supplier, filename):
    path = os.path.join(FIXTURE_DIR, supplier, filename)
    with open(path, "r", encoding="utf-8") as f:
        return f.read()

def compute_hash(payload):
    """Compute a stable hash of the payload for determinism checks."""
    s = json.dumps(payload, sort_keys=True)
    return hashlib.sha256(s.encode("utf-8")).hexdigest()

def test_daily_canary_flow(db_session, tmp_path):
    """
    Deterministic Canary:
    1. Scrapes fixture (OneCheq).
    2. Enriches via LLM Stub.
    3. Builds Listing Payload.
    4. Outputs JSON Report.
    """
    start_time = datetime.now()
    summary = {
        "scraped_count": 0,
        "enriched_count": 0,
        "images_processed": 0,
        "commands_created": 0,
        "failures": [],
        "payload_hash": None,
        "duration_seconds": 0.0,
        "timestamp": datetime.now(timezone.utc).isoformat()
    }
    
    try:
        # 1. Scrape Fixture (Stub Network)
        html_content = load_fixture("onecheq", "product.html")
        with patch("retail_os.scrapers.onecheq.scraper.get_html_via_httpx", return_value=html_content):
            raw_data = scrape_onecheq_product("https://onecheq.co.nz/products/canary-item")
        
        assert raw_data is not None, "Scrape fixture failed"
        summary["scraped_count"] = 1
        
        # 2. Normalize
        unified = normalize_onecheq_row(raw_data)
        unified["source_category"] = "canary-collection"
        
        images_list = [
            unified.get("photo1"), unified.get("photo2"), 
            unified.get("photo3"), unified.get("photo4")
        ]
        images_list = [x for x in images_list if x]
        summary["images_processed"] = len(images_list)
        
        # 3. Simulate DB Persist
        from retail_os.core.database import SupplierProduct, Supplier
        s = Supplier(id=99, name="CANARY_SUPPLIER", base_url="http://canary")
        db_session.add(s)
        db_session.flush()
        
        sp = SupplierProduct(
            supplier_id=99,
            external_sku="CANARY-001",
            title=unified["title"],
            description=unified["description"],
            cost_price=unified["buy_now_price"],
            images=images_list,
            specs=unified["specs"],
            source_category="test-cat",
            snapshot_hash="abc",
            last_scraped_at=datetime.now(timezone.utc)
        )
        db_session.add(sp)
        db_session.commit()
        db_session.refresh(sp)
        sp.supplier = s # Force loaded relationship
        
        # 4. Enrich & Prepare (Stub LLM & Images)
        # We manually set enriched fields instead of mocking LLM
        # since MarketplaceAdapter reads these directly from the model
        sp.enriched_title = "Enriched Canary Product"
        sp.enriched_description = "Better description generated by AI."
        sp.technical_specs = {"Brand": "FixtureBrand"}
        summary["enriched_count"] = 1
        
        # 5. Build Payload (MarketplaceAdapter)
        # Mock the components that fetch external data or check files
        with patch("retail_os.core.category_mapper.CategoryMapper.map_category", return_value="0001-0002"), \
             patch("retail_os.core.category_mapper.CategoryMapper.get_category_name", return_value="Mobile Phones"), \
             patch("retail_os.core.image_guard.guard.check_image", return_value={"is_safe": True, "reason": "Mocked"}), \
             patch("retail_os.core.image_guard.guard.is_active", return_value=True), \
             patch("retail_os.trademe.config.TradeMeConfig.MODE", "STANDARD"):
                             
            payload = MarketplaceAdapter.prepare_for_trademe(sp)
                
        # 6. Validation
        assert payload["title"] == "Enriched Canary Product" 
        assert payload["description"].startswith("Better description")
        assert payload["price"] > 200.0
        
        # Record Hash
        summary["payload_hash"] = compute_hash(payload)
        summary["commands_created"] = 1 # Successfully created draft payload implies 1 potential command
        
    except Exception as e:
        summary["failures"].append(str(e))
        raise e
    finally:
        summary["duration_seconds"] = (datetime.now() - start_time).total_seconds()
        
        # Output Report
        report_path = os.path.join(os.path.dirname(__file__), "../data/canary_report.json")
        os.makedirs(os.path.dirname(report_path), exist_ok=True)
        with open(report_path, "w") as f:
            json.dump(summary, f, indent=2)
            
    # Determinism Check (Manual Verification or CI Assertion)
    # Ideally, we assert payload_hash is a specific known value if inputs are fixed.
    # Given 'fixtures/scrapers/onecheq/product.html' is static, and mocks are static,
    # the hash should be stable.
    # We won't hardcode the hash yet to avoid fragility on first run, but it's captured.
